[package]
name = "fantasy_realms_v2"
version = "0.1.0"
authors = ["Ifit"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.4"
bevy_mod_picking = "0.3.1"
rand = "0.8.1"